image_hub/urls.py
from django.contrib import admin
from django.urls import path,include
import logging 
from django.conf.urls.static import static
from django.conf import settings
logger = logging.getLogger('django')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('image_hub_app.urls')),
    path('image-hub-admin/', include('image_hub_admin_app.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
logger.info("Url patters are",urlpatterns)

image_hub_admin_app/urls.py
from django.urls import path
from .views import HomePage,ImageAdminCategoryCreateView,ImageAdminCreateView
app_name = 'image_hub_admin_app'
urlpatterns = [
    path('',HomePage.as_view(),name = 'home_admin'),
    path('image-category-create/',ImageAdminCategoryCreateView.as_view(),name = 'image_category_create_admin'),
    path('image-create/',ImageAdminCreateView.as_view(),name = 'image_create_admin'),
    # path('image-create/',create_image_view,name = 'image_create_admin'),
]

image_hub_app/urls.py
from django.urls import path
from .views import HomePageView,ImageDetailView,ImageRedirectView

app_name = "image_hub_app"
urlpatterns = [
    path('home/', HomePageView.as_view() ,name="home"),
    path('detail/<int:pk>', ImageDetailView.as_view() ,name="image-details"),
    path('redirect/<int:pk>', ImageRedirectView.as_view() ,name="image-redirect"),
    
]

image_hub_admin_app/models.py
from django.db import models

# Create your models here.

image_hub_app/models.py
from django.db import models
# from django.shortcuts import reverse
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    category_name           = models.CharField(max_length=100,unique=True)
    title                   = models.CharField(max_length=100)
    description             = models.TextField()

    def __str__(self):
        return self.category_name

class ImageHub(models.Model):
    image                   = models.ImageField()
    title                   = models.CharField(max_length=100)
    number_of_people        = models.IntegerField(null=True,blank=False)
    description             = models.TextField()
    category                = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='cat')
    number_of_views         = models.IntegerField(verbose_name="view",default=0)
    number_of_downloads     = models.IntegerField(verbose_name="downloads",default=0)
    created_date            = models.DateField(auto_now_add=True,null=True,blank=True)
    
    class Meta:
        pass
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        
        return reverse('image-details',kwargs={id:self.id})    

image_hub_admin_app/forms.py
from django import forms
from image_hub_app.models import Category,ImageHub
import logging
logger = logging.getLogger('django')
class ImageCategoryCreateForm(forms.ModelForm):
    
    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
            'category_name': forms.TextInput(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'cols': 1, 'rows': 3}),
            # 'name': Textarea(attrs={'cols': 80, 'rows': 20}),
        }

        
class ImageCreateForm(forms.ModelForm):
    
    class Meta:
        model = ImageHub
        fields = ['image','title','number_of_people','description','category']
        widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control', 'cols': 1, 'rows': 3}),
            # 'name': Textarea(attrs={'cols': 80, 'rows': 20}),
        }
    def __init__(self, *args, **kwargs):
        super(ImageCreateForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            logger.info(field)
        # self.fields['image'].widget.attrs['class'] = ['form-file-input','form-control']
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['number_of_people'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['category'].widget.attrs['class'] = 'form-control'

image_hub_admin_app/views.py
import logging
from django.shortcuts import render,redirect
from django.views.generic import TemplateView,CreateView,DeleteView,DetailView
from .forms import ImageCategoryCreateForm, ImageCreateForm
from image_hub_app.models import Category,ImageHub
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.messages.views import SuccessMessageMixin
# Create your views here.
logger = logging.getLogger('django')

class HomePage(TemplateView):
    template_name = 'admin/home.html'
    
    def get_context_data(self,**kwargs):
        context        = super(HomePage,self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context
        
class ImageAdminCategoryCreateView(SuccessMessageMixin,CreateView):
    form_class          = ImageCategoryCreateForm
    template_name       = 'admin/image_category_create_from.html'
    success_url         = '/image-hub-admin/'
    success_message     = "sucess fully created"
class ImageAdminCreateView(SuccessMessageMixin,CreateView):
    form_class          = ImageCreateForm
    template_name       = 'admin/image_create_from.html'
    success_url         = '/image-hub-admin/'
    success_message     = "sucess fully created"

image_hub_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView,DeleteView,DetailView,RedirectView,FormView
import logging
from image_hub_app.models import ImageHub
from django.shortcuts import  get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from .mixins import FindMethodMixin,SerializeMixin
import json
from django.http import JsonResponse
from django.core import serializers
# Create your views here.

logger = logging.getLogger('django')

class HomePageView(TemplateView,FindMethodMixin,SerializeMixin):
   
    template_name = "image_hub_app/home.html"
    model = ImageHub

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(HomePageView, self).dispatch(request, *args, **kwargs)

    def post(self,request,*args,**kwargs):
        context             = super(HomePageView,self).get_context_data(**kwargs)
        context['obj_list'] = self.model.objects.all()
        print(request.body)
        qs_json             = self.serialize(request,*args,**kwargs)
        return JsonResponse(qs_json,safe=False)


    # def get(self, request, *args, **kwargs):
    #     context = self.get_context_data(**kwargs)
    #     return self.render_to_response(context)
   

    def get_context_data(self,**kwargs):
        context = super(HomePageView,self).get_context_data(**kwargs)
        if self.request.body:

            print(self.request.body)
            json_data = json.loads(request.body)
        
            return context
        else:
            context['obj_list'] = ImageHub.objects.all()[0:3]
            return context  
    

class ImageDetailView(DetailView):
    model               = ImageHub
    template_name       = 'image_hub_app/image_details.html'
    context_object_name = 'obj'
    
    
    def get_object(self):
        try:
            obj = get_object_or_404(ImageHub,pk=self.kwargs.get('pk'))
        except ObjectDoesNotExist:
            return obj
        obj.number_of_views +=1
        obj.save()
        return obj

class ImageRedirectView(RedirectView):
    pattern_name        = 'image_hub_app:image-details'
    permanent           = False
    query_string        = True

    def get_redirect_url(self, *args, **kwargs):
        image = get_object_or_404(ImageHub, pk=kwargs['pk'])
        print("Get redirect has been called",image)
        image.number_of_downloads+= 1
        image.save()
        
        return super().get_redirect_url(*args, **kwargs)


        

image_hub_app/templates/image_hub_app/home.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">    
{% endblock %}

{% block js %}
    <script src="{% static 'js/image_hub_app.js' %}"></script>
{% endblock  %}
{% block navbar %}
    {% include "image_hub_app/nav_bar.html" %}
{% endblock %}
{% block content %}
    {% if obj_list  %}
    <div class="container-fluid">
        <div class="main-content">
            <div class="row">
                <div class="col-md-10 col-lg-12 col-md-mt-4">
                    <div class="column-content">
                        <div class="row">
                            <div class="col-md-3 mt-3">
                                <div class="left-column-content shadow p-3">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <img src="{% static 'images/catecon.png' %}" class="w-100" alt="Nothing found">
                                        </div>
                                        <div class="col-md-8">
                                            <h2>Here the description is</h2>
                                            <p>this is very beautiful website that i designed fou you</p>                                            
                                        </div>
                                    </div>
                                    <div class="row mt-3">
                                        <div class="col-md-6 d-flex justify-content-end  ">
                                            <div class="btn btn-info btn-sm p-2">Upload Image</div>
                                        </div>
                                        <div class="col-md-6 d-flex justify-content-end  ">
                                            <div class="btn btn-light btn-sm p-2 ">Read More </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mid-column-content shadow p-2 mt-3">
                                    {% for obj in obj_list %}
                                    <div class="card mb-3 mx-auto " style="max-width: 540px;">
                                        <div class="row g-0 ">
                                          <div class="col-md-4 p-2 d-flex image-overlay align-items-center justify-content-center">
                                            <img src="{{obj.image.url}}" class="img-thumbnail image " style="max-width: 100%;min-height: 170px "  alt="...">
                                            <div class="middle">
                                                <div class="text"> <a href="{% url 'image_hub_app:image-details' pk=obj.id %}" class="btn btn-info rounded-0  text-uppercase text-white"> view </a>  </div>
                                                
                                            </div>
                                            </div>
                                          <div class="col-md-8">
                                            <div class="card-body  ">
                                                <div class="row">
                                                    <div class="col-md-8">
                                                        <h5 class="card-title image-title">{{obj.title}}</h5>
                                                    </div>
                                                    <div class="col-md-4 ">
                                                        <div class="span float-right">
                                                            {% if obj.number_of_views != 0 %}
                                                            <span class="badge rounded-pill bg-success">viewed</span>
                                                            {% else %}
                                                            <span class="badge rounded-pill bg-info">new</span>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <p class="card-text card-text-description">{{obj.description}}</p>
                                                    </div>
                                                </div>
                                                <div class="row last-row mt-5 ">
                                                    <div class="col-md-4">
                                                        <p class="card-text timing-info "><small class="text-muted"><i class="far fa-clock"></i> updaed at <span class="text-info text-created-date"> <small>{{obj.created_date}}</small></span> </small></p>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <p class="card-text timing-info"><small class="text-muted"><i class="fas fa-eye"></i> views <span class="text-info"> {{obj.number_of_views}}</span> </small></p>
                                                    </div>
                                                    <div class="col-md-4 ">
                                                        <p class="card-text timing-info "><small class="text-muted"><i class="fas fa-angle-double-down"></i></i> downloads <span class="text-info"> {{obj.number_of_downloads}}</span> </small></p>
                                                    </div>
                                                </div>
                                            </div>
                                          </div>
                                        </div>
                                    </div>
                                    <hr>
                                    {% endfor %}
                                    <div id="scrollel"></div>
                                </div>
                            </div>
                            <div class="col-md-3 mt-3">
                                <div class="right-column-content shadow mb-3">
                                    <div class="card border border-info">
                                        <div class="card-body">
                                          This is some text within a card body.
                                        </div>
                                    </div>
                                </div>
                                <div class="card text-body   mb-3" style="max-width: 100%; min-height:300px;">
                                    <div class="card-header bg-info text-white">Short Info of Image</div>
                                    <div class="card-body">
                                      <h5 class="card-title">Info card title</h5>
                                      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                    </div>
                                  </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
        <h1>Nothing toshow</h1>
    {% endif %}
{% endblock %}

image_hub_app/templates/image_hub_app/image_details.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">    
{% endblock %}

{% block navbar %}
    {% include "image_hub_app/nav_bar.html" %}
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="main-content">
            <div class="row mt-4 ">
                <div class="col-md-10  mx-auto col-md-mt-4">
                    <div class="column-content">
                        <div class="row">
                            <div class="col-md-4 ">
                                <div class="left-column-content ">
                                    <img src="{{ obj.image.url }}" class="img-thumbnail  " style="width: 400px;" alt="" srcset="" download>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="image-details-right-side-container border-sm">
                                    <h1 class="text-muted">{{obj.title}}</h1>
                                    <hr>
                                    <div class="row">
                                        <div class="col-md-7">
                                            <div class="image-details-right-side-container-left-side">
                                                <h3 class="text-dark">{{obj.description}}</h3>
                                            </div>
                                        </div>
                                        <div class="col-md-5 d-flex">
                                            <div class="image-details-right-side-container-left-side ml-auto text-muted">
                                                <span><small>Ratings</small></span>
                                                <i class="far fa-star m-1"></i>
                                                <i class="far fa-star m-1"></i>
                                                <i class="far fa-star m-1"></i>
                                                <i class="far fa-star m-1"></i>
                                                <i class="far fa-star m-1"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mt-5">
                                        <div class="col-md-6">
                                            <div class="cateogory-details shadow-sm" >
                                                <p>{{obj.category.title}}</p>
                                                <small>{{obj.category.category_name}}</small>
                                                
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="cateogory-details shadow-sm" >
                                                <div class="category-description text-right">
                                                    <small class="">{{obj.category.description}}</small>
                                                </div>
                                                
                                            </div>
                                        </div>
                                        
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <a href="{% url 'image_hub_app:image-redirect' pk=obj.id %}" class="btn btn-info">Download</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

image_hub_app/templates/image_hub_app/nav_bar.html
<div class="container-fluid px-0">
    <nav class="navbar navbar-expand-lg  bg-nav">
        <div class="container-fluid">
          <a class="navbar-brand text-white h2" href="#">Image<span class="text-color text-uppercase font-weight-bolder ml-1">Hub</span> </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarNav">
            <form class="d-flex ml-5 w-50">
              <input class="form-control ml-auto w-100 p-1 search-bar" type="search" placeholder="Search" aria-label="Search">
              <i class="fas fa-search text-muted search-bar-icon text-muted" ></i>
            </form>
            <ul class="navbar-nav ml-auto mr-5">
              <li class="nav-item">
                
              </li>
              <li class="nav-item">
                
              </li>
              <li class="nav-item">
                
              </li>
              
            </ul>
          </div>
        </div>
      </nav>
    
</div>

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/67ec475b06.js" crossorigin="anonymous"></script>
    <title>Image Hub</title>
     <link rel = "icon" href ="{% static 'images/catecon.png' %}"  
        type = "image/icon">
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
    
        <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@200&display=swap" rel="stylesheet">
    {% block css %}
    {% endblock %}
    <script src="{% static 'js/jq.js' %}"></script> 
    <script type="text/javascript">
      function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');
    </script>
    <script type="text/javascript">
      let result  = 3;
    </script>             
  </head>
  <body>
    {% block navbar %}

    {% endblock %}
    {% block content %}

    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- Popper.js first, then Bootstrap JS -->
    {% block js %}

    {% endblock %}
    <!-- <script src="{% static 'js/image_hub_app.js' %}"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
  </body>
</html>